theme: jekyll-theme-minimal
description: a benchmark dataset for training and evaluating global cloud classification models

url: "http://frontierdevelopmentlab.github.io/CUMULO/"

logo: "./docs/images/cumulo.png"
