theme: jekyll-theme-minimal
description: a benchmark dataset for training and evaluating global cloud classification models

logo: https://github.com/FrontierDevelopmentLab/CUMULO/blob/master/docs/images/logo.png