theme: jekyll-theme-minimal
description: a benchmark dataset for training and evaluating global cloud classification models

logo: "./docs/images/cumulo.png"

url: "http://frontierdevelopmentlab.github.io/CUMULO/"
